### ISSUE TITLE
"k1 xy joint v3.1.3mf" being flagged as Archive.Bomb by Baidu in VirusTotal

### ISSUE THREAD

**Issue by Su-Plx** [D3vil-Design/K1-Hardware-Mods#1]
Hi Omran!

First off, thank you so much for all the assistance you've been offering the K1 community---I know that I, and a lot of other folks who have bought one, have honestly felt more supported and seen in the tutorial and mod videos that you've made, than by the support offered from Creality themselves. It can often be thankless, and dealing with Creality can be incredibly frustrating, so I want you to know that, at least for me, your videos are the ones I go to first whenever I'm having trouble with the printer, need to remember how something was put together, get ideas for improvements, etc.. And the music isn't bad, either 😎️👍️

The work you've put into refining the movement system is the first major step forward into making the K1 a truly consistent and reliable print platform. Thank you so much!

I wanted to give you a heads up that for whatever reason, Baidu via VirusTotal is flagging the file "k1 xy joint v3.1.3mf" as an archive/zip bomb. I grabbed a couple random 3mf files from Printables with a similar size/number of compressed files, and scanned them to see if Baidu was flagging all 3mf files, but I only saw that behavior from the 3mf I got from your github repo.

I don't think it is intentional, and haven't flagged or reported the file to github or anything. My guess is that the easiest fix might be to try repacking the model into a new 3mf and re-uploading, but I'm not set up to test that sort of thing, so I can't say for sure.

Thank you again for the incredible help you've been to the K1 community!

-Su_Plx

**Comment by Omranello** [comment]
Bro thanks alot for the sweet email , this worth it all.

I will upload the STL instead .. it's better I guess.

Thanks for the heads up,  I would not have noticed it myself.

If anything I can help u with please contact me ... always here to help .

Thanks again

**Comment by Omranello** [comment]
New files uploaded .
