### ISSUE TITLE
knomi issues

### ISSUE THREAD

**Issue by kwotattoos** [D3vil-Design/K1-Hardware-Mods#3]
in the read me it says to follow btt info for the knomi but the required macro gave me errors and locked up my homing. what should we add to get the knomi to show all the different animations?

**Comment by Omranello** [comment]
> in the read me it says to follow btt info for the knomi but the required macro gave me errors and locked up my homing. what should we add to get the knomi to show all the different animations?

The Macros are not needed , (only for homing and leveling animation /information) 
Once the Knomi is linked fine wifi thro the Hello screen by adding the ( IP address: port ) all should work fine.

**Comment by lvlacleod** [comment]
> in the read me it says to follow btt info for the knomi but the required macro gave me errors and locked up my homing. what should we add to get the knomi to show all the different animations?

To get Homing and bed mesh working follow this. Took me a while to figure it all out but finally got both homing and bed mesh working with knomi.
https://github.com/bigtreetech/KNOMI/pull/5

**Comment by Omranello** [comment]
Thank you , ill go ahead and close this as we will add it to the main page
