### ISSUE TITLE
Bearings

### ISSUE THREAD

**Issue by bronsn** [D3vil-Design/K1-Hardware-Mods#5]
Hello,
great work from you and your Team/Partner what ever , glad that you give us such good impressions and information about the K1.
I have damaged my Bearing above the big idler over the Stepper motor , so i stopped the work and put the damaged back (he works but i think he will break soon ), do you know wich bearings are there in or which number they have ?

Other i have to disamble the printer again before i can purchase some new one.
Sry i know this is not the Issue with your design as itself, but perhaps you can help me :)

Regards

**Comment by DerrickDarrell** [comment]
youre talking about the bearing on the stepper shaft?

**Comment by bronsn** [comment]
yes )

**Comment by Omranello** [comment]
kindly do join our discord for those related issues . https://discord.gg/vPr5DjfHUJ
