### ISSUE TITLE
Gantry V2.0

### ISSUE THREAD

**Issue by sbtoonz** [D3vil-Design/K1-Hardware-Mods#6]
![image](https://github.com/D3vil-Design/K1-Hardware-Mods/assets/67915879/18fa0d3e-8b80-4fdb-95a7-bb65aeb1cc03)
Cant print the idlers are floating in midair 

Can  you potentially re up with them all split?

**Comment by sbtoonz** [comment]
can split in orcaslicer

**Comment by sbtoonz** [comment]
![image](https://github.com/D3vil-Design/K1-Hardware-Mods/assets/67915879/c2b7ccab-022b-464d-92ce-a6f6618c2c8d)
part is mis organized in the STL on git

**Comment by DerrickDarrell** [comment]
right click>split to objects
