### ISSUE TITLE
How about adapating A new motherboard for Vanilla Klipper

### ISSUE THREAD

**Issue by sismo99** [D3vil-Design/K1-Hardware-Mods#7]
How about adapting a new motherboard to be able to use Klipper Vanilla, I was thinking about one from Big Tree Tech, specifically a Manta 5P and using a 5-inch BTT SPI (or even HDMI) screen to use Klipperscreen. I have been analyzing the original motherboard but the CANBus parts and the Strain gauges are complicated for me. I hope you can help me.

**Comment by sbtoonz** [comment]
> How about adapting a new motherboard to be able to use Klipper Vanilla, I was thinking about one from Big Tree Tech, specifically a Manta 5P and using a 5-inch BTT SPI (or even HDMI) screen to use Klipperscreen. I have been analyzing the original motherboard but the CANBus parts and the Strain gauges are complicated for me. I hope you can help me.

Visit our discord for more 

I have this operating as you describe

https://github.com/sbtoonz/k1_klipper

repo I am operating my m5p k1 off of
